name: Build & Test pull requests
# Run workflow on every pull request to the master branch
on:
  pull_request:
    branches:
      - master
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build-and-test:
    # use ubuntu-latest
    runs-on: ubuntu-latest
    strategy:
     matrix:
        dotnet-version: ['7.0.x']

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3
  
    # Cache NuGet packages
    - name: Cache NuGet packages
      uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    # sets up .NET Core SDK 7.0.x
    - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v3.0.3
      with:
        dotnet-version: ${{ matrix.dotnet-version }}

    # Restore dependencies
    - name: Restore dependencies
      run: dotnet restore

    # Install dotnet wasm buildtools workload
    - name: Install .NET WASM Build Tools
      run: dotnet workload install wasm-tools

    # Cache build outputs
    - name: Cache build outputs
      uses: actions/cache@v3
      with:
        path: |
          **/bin
          **/obj
        key: ${{ runner.os }}-build-${{ env.cache-version }}
        restore-keys: |
          ${{ runner.os }}-build-

    # Build the project
    - name: Build the project
      run: dotnet build --configuration Release --no-restore

    # Test the project
    - name: Test the project
      run: dotnet test --no-restore --verbosity normal